language: ruby
rvm:
  - jruby
cache: bundler
bundler_args: "--binstubs --without documentation --path ../bundle --retry=3 --jobs=3"
before_script: bundle exec jbundle install
script: bundle exec rspec spec --require spec_helper

jdk:
  - oraclejdk8

#addons:
#  code_climate:
#    repo_token: